apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus-exporter'
        static_configs:
          - targets: ['prometheus-exporter:9394']
        metrics_path: '/metrics'