apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter
spec:
  selector:
    app: prometheus-exporter
  ports:
    - protocol: TCP
      port: 9394
      targetPort: 9394
  type: ClusterIP
  